// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"blog-server/ent/comment"
	"blog-server/ent/link"
	"blog-server/ent/linkcategory"
	"blog-server/ent/post"
	"blog-server/ent/postcategory"
	"blog-server/ent/posttag"
	"blog-server/ent/schema"
	"blog-server/ent/user"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	commentMixin := schema.Comment{}.Mixin()
	commentMixinHooks1 := commentMixin[1].Hooks()
	comment.Hooks[0] = commentMixinHooks1[0]
	commentMixinInters1 := commentMixin[1].Interceptors()
	comment.Interceptors[0] = commentMixinInters1[0]
	commentMixinFields0 := commentMixin[0].Fields()
	_ = commentMixinFields0
	commentFields := schema.Comment{}.Fields()
	_ = commentFields
	// commentDescCreatedAt is the schema descriptor for created_at field.
	commentDescCreatedAt := commentMixinFields0[1].Descriptor()
	// comment.DefaultCreatedAt holds the default value on creation for the created_at field.
	comment.DefaultCreatedAt = commentDescCreatedAt.Default.(func() time.Time)
	// commentDescUpdatedAt is the schema descriptor for updated_at field.
	commentDescUpdatedAt := commentMixinFields0[2].Descriptor()
	// comment.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	comment.DefaultUpdatedAt = commentDescUpdatedAt.Default.(func() time.Time)
	// comment.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	comment.UpdateDefaultUpdatedAt = commentDescUpdatedAt.UpdateDefault.(func() time.Time)
	linkMixin := schema.Link{}.Mixin()
	linkMixinHooks1 := linkMixin[1].Hooks()
	link.Hooks[0] = linkMixinHooks1[0]
	linkMixinInters1 := linkMixin[1].Interceptors()
	link.Interceptors[0] = linkMixinInters1[0]
	linkMixinFields0 := linkMixin[0].Fields()
	_ = linkMixinFields0
	linkFields := schema.Link{}.Fields()
	_ = linkFields
	// linkDescCreatedAt is the schema descriptor for created_at field.
	linkDescCreatedAt := linkMixinFields0[1].Descriptor()
	// link.DefaultCreatedAt holds the default value on creation for the created_at field.
	link.DefaultCreatedAt = linkDescCreatedAt.Default.(func() time.Time)
	// linkDescUpdatedAt is the schema descriptor for updated_at field.
	linkDescUpdatedAt := linkMixinFields0[2].Descriptor()
	// link.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	link.DefaultUpdatedAt = linkDescUpdatedAt.Default.(func() time.Time)
	// link.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	link.UpdateDefaultUpdatedAt = linkDescUpdatedAt.UpdateDefault.(func() time.Time)
	// linkDescDescription is the schema descriptor for description field.
	linkDescDescription := linkFields[0].Descriptor()
	// link.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	link.DescriptionValidator = linkDescDescription.Validators[0].(func(string) error)
	// linkDescEnabled is the schema descriptor for enabled field.
	linkDescEnabled := linkFields[1].Descriptor()
	// link.DefaultEnabled holds the default value on creation for the enabled field.
	link.DefaultEnabled = linkDescEnabled.Default.(bool)
	// linkDescName is the schema descriptor for name field.
	linkDescName := linkFields[2].Descriptor()
	// link.NameValidator is a validator for the "name" field. It is called by the builders before save.
	link.NameValidator = linkDescName.Validators[0].(func(string) error)
	// linkDescSortOrder is the schema descriptor for sort_order field.
	linkDescSortOrder := linkFields[3].Descriptor()
	// link.DefaultSortOrder holds the default value on creation for the sort_order field.
	link.DefaultSortOrder = linkDescSortOrder.Default.(int)
	// linkDescURL is the schema descriptor for url field.
	linkDescURL := linkFields[4].Descriptor()
	// link.URLValidator is a validator for the "url" field. It is called by the builders before save.
	link.URLValidator = linkDescURL.Validators[0].(func(string) error)
	// linkDescAvatar is the schema descriptor for avatar field.
	linkDescAvatar := linkFields[5].Descriptor()
	// link.AvatarValidator is a validator for the "avatar" field. It is called by the builders before save.
	link.AvatarValidator = linkDescAvatar.Validators[0].(func(string) error)
	linkcategoryMixin := schema.LinkCategory{}.Mixin()
	linkcategoryMixinHooks1 := linkcategoryMixin[1].Hooks()
	linkcategory.Hooks[0] = linkcategoryMixinHooks1[0]
	linkcategoryMixinInters1 := linkcategoryMixin[1].Interceptors()
	linkcategory.Interceptors[0] = linkcategoryMixinInters1[0]
	linkcategoryMixinFields0 := linkcategoryMixin[0].Fields()
	_ = linkcategoryMixinFields0
	linkcategoryFields := schema.LinkCategory{}.Fields()
	_ = linkcategoryFields
	// linkcategoryDescCreatedAt is the schema descriptor for created_at field.
	linkcategoryDescCreatedAt := linkcategoryMixinFields0[1].Descriptor()
	// linkcategory.DefaultCreatedAt holds the default value on creation for the created_at field.
	linkcategory.DefaultCreatedAt = linkcategoryDescCreatedAt.Default.(func() time.Time)
	// linkcategoryDescUpdatedAt is the schema descriptor for updated_at field.
	linkcategoryDescUpdatedAt := linkcategoryMixinFields0[2].Descriptor()
	// linkcategory.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	linkcategory.DefaultUpdatedAt = linkcategoryDescUpdatedAt.Default.(func() time.Time)
	// linkcategory.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	linkcategory.UpdateDefaultUpdatedAt = linkcategoryDescUpdatedAt.UpdateDefault.(func() time.Time)
	// linkcategoryDescName is the schema descriptor for name field.
	linkcategoryDescName := linkcategoryFields[0].Descriptor()
	// linkcategory.NameValidator is a validator for the "name" field. It is called by the builders before save.
	linkcategory.NameValidator = linkcategoryDescName.Validators[0].(func(string) error)
	// linkcategoryDescSortOrder is the schema descriptor for sort_order field.
	linkcategoryDescSortOrder := linkcategoryFields[1].Descriptor()
	// linkcategory.DefaultSortOrder holds the default value on creation for the sort_order field.
	linkcategory.DefaultSortOrder = linkcategoryDescSortOrder.Default.(int)
	postMixin := schema.Post{}.Mixin()
	postMixinHooks1 := postMixin[1].Hooks()
	post.Hooks[0] = postMixinHooks1[0]
	postMixinInters1 := postMixin[1].Interceptors()
	post.Interceptors[0] = postMixinInters1[0]
	postMixinFields0 := postMixin[0].Fields()
	_ = postMixinFields0
	postFields := schema.Post{}.Fields()
	_ = postFields
	// postDescCreatedAt is the schema descriptor for created_at field.
	postDescCreatedAt := postMixinFields0[1].Descriptor()
	// post.DefaultCreatedAt holds the default value on creation for the created_at field.
	post.DefaultCreatedAt = postDescCreatedAt.Default.(func() time.Time)
	// postDescUpdatedAt is the schema descriptor for updated_at field.
	postDescUpdatedAt := postMixinFields0[2].Descriptor()
	// post.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	post.DefaultUpdatedAt = postDescUpdatedAt.Default.(func() time.Time)
	// post.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	post.UpdateDefaultUpdatedAt = postDescUpdatedAt.UpdateDefault.(func() time.Time)
	// postDescTitle is the schema descriptor for title field.
	postDescTitle := postFields[1].Descriptor()
	// post.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	post.TitleValidator = postDescTitle.Validators[0].(func(string) error)
	// postDescSummary is the schema descriptor for summary field.
	postDescSummary := postFields[2].Descriptor()
	// post.SummaryValidator is a validator for the "summary" field. It is called by the builders before save.
	post.SummaryValidator = postDescSummary.Validators[0].(func(string) error)
	// postDescCover is the schema descriptor for cover field.
	postDescCover := postFields[4].Descriptor()
	// post.CoverValidator is a validator for the "cover" field. It is called by the builders before save.
	post.CoverValidator = postDescCover.Validators[0].(func(string) error)
	// postDescViewCount is the schema descriptor for view_count field.
	postDescViewCount := postFields[6].Descriptor()
	// post.DefaultViewCount holds the default value on creation for the view_count field.
	post.DefaultViewCount = postDescViewCount.Default.(uint)
	postcategoryMixin := schema.PostCategory{}.Mixin()
	postcategoryMixinHooks1 := postcategoryMixin[1].Hooks()
	postcategory.Hooks[0] = postcategoryMixinHooks1[0]
	postcategoryMixinInters1 := postcategoryMixin[1].Interceptors()
	postcategory.Interceptors[0] = postcategoryMixinInters1[0]
	postcategoryMixinFields0 := postcategoryMixin[0].Fields()
	_ = postcategoryMixinFields0
	postcategoryFields := schema.PostCategory{}.Fields()
	_ = postcategoryFields
	// postcategoryDescCreatedAt is the schema descriptor for created_at field.
	postcategoryDescCreatedAt := postcategoryMixinFields0[1].Descriptor()
	// postcategory.DefaultCreatedAt holds the default value on creation for the created_at field.
	postcategory.DefaultCreatedAt = postcategoryDescCreatedAt.Default.(func() time.Time)
	// postcategoryDescUpdatedAt is the schema descriptor for updated_at field.
	postcategoryDescUpdatedAt := postcategoryMixinFields0[2].Descriptor()
	// postcategory.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	postcategory.DefaultUpdatedAt = postcategoryDescUpdatedAt.Default.(func() time.Time)
	// postcategory.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	postcategory.UpdateDefaultUpdatedAt = postcategoryDescUpdatedAt.UpdateDefault.(func() time.Time)
	// postcategoryDescName is the schema descriptor for name field.
	postcategoryDescName := postcategoryFields[0].Descriptor()
	// postcategory.NameValidator is a validator for the "name" field. It is called by the builders before save.
	postcategory.NameValidator = postcategoryDescName.Validators[0].(func(string) error)
	// postcategoryDescSlug is the schema descriptor for slug field.
	postcategoryDescSlug := postcategoryFields[1].Descriptor()
	// postcategory.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	postcategory.SlugValidator = postcategoryDescSlug.Validators[0].(func(string) error)
	posttagMixin := schema.PostTag{}.Mixin()
	posttagMixinHooks1 := posttagMixin[1].Hooks()
	posttag.Hooks[0] = posttagMixinHooks1[0]
	posttagMixinInters1 := posttagMixin[1].Interceptors()
	posttag.Interceptors[0] = posttagMixinInters1[0]
	posttagMixinFields0 := posttagMixin[0].Fields()
	_ = posttagMixinFields0
	posttagFields := schema.PostTag{}.Fields()
	_ = posttagFields
	// posttagDescCreatedAt is the schema descriptor for created_at field.
	posttagDescCreatedAt := posttagMixinFields0[1].Descriptor()
	// posttag.DefaultCreatedAt holds the default value on creation for the created_at field.
	posttag.DefaultCreatedAt = posttagDescCreatedAt.Default.(func() time.Time)
	// posttagDescUpdatedAt is the schema descriptor for updated_at field.
	posttagDescUpdatedAt := posttagMixinFields0[2].Descriptor()
	// posttag.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	posttag.DefaultUpdatedAt = posttagDescUpdatedAt.Default.(func() time.Time)
	// posttag.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	posttag.UpdateDefaultUpdatedAt = posttagDescUpdatedAt.UpdateDefault.(func() time.Time)
	// posttagDescName is the schema descriptor for name field.
	posttagDescName := posttagFields[0].Descriptor()
	// posttag.NameValidator is a validator for the "name" field. It is called by the builders before save.
	posttag.NameValidator = posttagDescName.Validators[0].(func(string) error)
	// posttagDescSlug is the schema descriptor for slug field.
	posttagDescSlug := posttagFields[1].Descriptor()
	// posttag.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	posttag.SlugValidator = posttagDescSlug.Validators[0].(func(string) error)
	userMixin := schema.User{}.Mixin()
	userMixinHooks1 := userMixin[1].Hooks()
	user.Hooks[0] = userMixinHooks1[0]
	userMixinInters1 := userMixin[1].Interceptors()
	user.Interceptors[0] = userMixinInters1[0]
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields0[1].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields0[2].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescUUID is the schema descriptor for uuid field.
	userDescUUID := userFields[0].Descriptor()
	// user.DefaultUUID holds the default value on creation for the uuid field.
	user.DefaultUUID = userDescUUID.Default.(func() uuid.UUID)
	// userDescAvatar is the schema descriptor for avatar field.
	userDescAvatar := userFields[1].Descriptor()
	// user.AvatarValidator is a validator for the "avatar" field. It is called by the builders before save.
	user.AvatarValidator = userDescAvatar.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[2].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[3].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[5].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
}

const (
	Version = "v0.14.5"                                         // Version of ent codegen.
	Sum     = "h1:Rj2WOYJtCkWyFo6a+5wB3EfBRP0rnx1fMk6gGA0UUe4=" // Sum of ent codegen.
)
