// Code generated by ent, DO NOT EDIT.

package postcategoryrelation

import (
	"blog-server/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// PostID applies equality check predicate on the "post_id" field. It's identical to PostIDEQ.
func PostID(v uint) predicate.PostCategoryRelation {
	return predicate.PostCategoryRelation(sql.FieldEQ(FieldPostID, v))
}

// PostCategoryID applies equality check predicate on the "post_category_id" field. It's identical to PostCategoryIDEQ.
func PostCategoryID(v uint) predicate.PostCategoryRelation {
	return predicate.PostCategoryRelation(sql.FieldEQ(FieldPostCategoryID, v))
}

// PostIDEQ applies the EQ predicate on the "post_id" field.
func PostIDEQ(v uint) predicate.PostCategoryRelation {
	return predicate.PostCategoryRelation(sql.FieldEQ(FieldPostID, v))
}

// PostIDNEQ applies the NEQ predicate on the "post_id" field.
func PostIDNEQ(v uint) predicate.PostCategoryRelation {
	return predicate.PostCategoryRelation(sql.FieldNEQ(FieldPostID, v))
}

// PostIDIn applies the In predicate on the "post_id" field.
func PostIDIn(vs ...uint) predicate.PostCategoryRelation {
	return predicate.PostCategoryRelation(sql.FieldIn(FieldPostID, vs...))
}

// PostIDNotIn applies the NotIn predicate on the "post_id" field.
func PostIDNotIn(vs ...uint) predicate.PostCategoryRelation {
	return predicate.PostCategoryRelation(sql.FieldNotIn(FieldPostID, vs...))
}

// PostCategoryIDEQ applies the EQ predicate on the "post_category_id" field.
func PostCategoryIDEQ(v uint) predicate.PostCategoryRelation {
	return predicate.PostCategoryRelation(sql.FieldEQ(FieldPostCategoryID, v))
}

// PostCategoryIDNEQ applies the NEQ predicate on the "post_category_id" field.
func PostCategoryIDNEQ(v uint) predicate.PostCategoryRelation {
	return predicate.PostCategoryRelation(sql.FieldNEQ(FieldPostCategoryID, v))
}

// PostCategoryIDIn applies the In predicate on the "post_category_id" field.
func PostCategoryIDIn(vs ...uint) predicate.PostCategoryRelation {
	return predicate.PostCategoryRelation(sql.FieldIn(FieldPostCategoryID, vs...))
}

// PostCategoryIDNotIn applies the NotIn predicate on the "post_category_id" field.
func PostCategoryIDNotIn(vs ...uint) predicate.PostCategoryRelation {
	return predicate.PostCategoryRelation(sql.FieldNotIn(FieldPostCategoryID, vs...))
}

// HasPost applies the HasEdge predicate on the "post" edge.
func HasPost() predicate.PostCategoryRelation {
	return predicate.PostCategoryRelation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, PostColumn),
			sqlgraph.Edge(sqlgraph.M2O, false, PostTable, PostColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPostWith applies the HasEdge predicate on the "post" edge with a given conditions (other predicates).
func HasPostWith(preds ...predicate.Post) predicate.PostCategoryRelation {
	return predicate.PostCategoryRelation(func(s *sql.Selector) {
		step := newPostStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCategory applies the HasEdge predicate on the "category" edge.
func HasCategory() predicate.PostCategoryRelation {
	return predicate.PostCategoryRelation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, CategoryColumn),
			sqlgraph.Edge(sqlgraph.M2O, false, CategoryTable, CategoryColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCategoryWith applies the HasEdge predicate on the "category" edge with a given conditions (other predicates).
func HasCategoryWith(preds ...predicate.PostCategory) predicate.PostCategoryRelation {
	return predicate.PostCategoryRelation(func(s *sql.Selector) {
		step := newCategoryStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PostCategoryRelation) predicate.PostCategoryRelation {
	return predicate.PostCategoryRelation(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PostCategoryRelation) predicate.PostCategoryRelation {
	return predicate.PostCategoryRelation(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PostCategoryRelation) predicate.PostCategoryRelation {
	return predicate.PostCategoryRelation(sql.NotPredicates(p))
}
