// Code generated by ent, DO NOT EDIT.

package posttagrelation

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the posttagrelation type in the database.
	Label = "post_tag_relation"
	// FieldPostID holds the string denoting the post_id field in the database.
	FieldPostID = "post_id"
	// FieldPostTagID holds the string denoting the post_tag_id field in the database.
	FieldPostTagID = "post_tag_id"
	// EdgePost holds the string denoting the post edge name in mutations.
	EdgePost = "post"
	// EdgeTag holds the string denoting the tag edge name in mutations.
	EdgeTag = "tag"
	// PostFieldID holds the string denoting the ID field of the Post.
	PostFieldID = "id"
	// PostTagFieldID holds the string denoting the ID field of the PostTag.
	PostTagFieldID = "id"
	// Table holds the table name of the posttagrelation in the database.
	Table = "post_tag_relations"
	// PostTable is the table that holds the post relation/edge.
	PostTable = "post_tag_relations"
	// PostInverseTable is the table name for the Post entity.
	// It exists in this package in order to avoid circular dependency with the "post" package.
	PostInverseTable = "posts"
	// PostColumn is the table column denoting the post relation/edge.
	PostColumn = "post_id"
	// TagTable is the table that holds the tag relation/edge.
	TagTable = "post_tag_relations"
	// TagInverseTable is the table name for the PostTag entity.
	// It exists in this package in order to avoid circular dependency with the "posttag" package.
	TagInverseTable = "post_tags"
	// TagColumn is the table column denoting the tag relation/edge.
	TagColumn = "post_tag_id"
)

// Columns holds all SQL columns for posttagrelation fields.
var Columns = []string{
	FieldPostID,
	FieldPostTagID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the PostTagRelation queries.
type OrderOption func(*sql.Selector)

// ByPostID orders the results by the post_id field.
func ByPostID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPostID, opts...).ToFunc()
}

// ByPostTagID orders the results by the post_tag_id field.
func ByPostTagID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPostTagID, opts...).ToFunc()
}

// ByPostField orders the results by post field.
func ByPostField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPostStep(), sql.OrderByField(field, opts...))
	}
}

// ByTagField orders the results by tag field.
func ByTagField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTagStep(), sql.OrderByField(field, opts...))
	}
}
func newPostStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, PostColumn),
		sqlgraph.To(PostInverseTable, PostFieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, PostTable, PostColumn),
	)
}
func newTagStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, TagColumn),
		sqlgraph.To(TagInverseTable, PostTagFieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, TagTable, TagColumn),
	)
}
