// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CommentsColumns holds the columns for the "comments" table.
	CommentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
	}
	// CommentsTable holds the schema information for the "comments" table.
	CommentsTable = &schema.Table{
		Name:       "comments",
		Columns:    CommentsColumns,
		PrimaryKey: []*schema.Column{CommentsColumns[0]},
	}
	// LinksColumns holds the columns for the "links" table.
	LinksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "enabled", Type: field.TypeBool, Default: false},
		{Name: "name", Type: field.TypeString, Size: 100},
		{Name: "sort_order", Type: field.TypeInt, Default: 0},
		{Name: "url", Type: field.TypeString, Unique: true, Size: 255},
		{Name: "avatar", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"normal", "abnormal"}, Default: "normal"},
		{Name: "category_id", Type: field.TypeUint, Nullable: true},
	}
	// LinksTable holds the schema information for the "links" table.
	LinksTable = &schema.Table{
		Name:       "links",
		Columns:    LinksColumns,
		PrimaryKey: []*schema.Column{LinksColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "links_link_categories_links",
				Columns:    []*schema.Column{LinksColumns[11]},
				RefColumns: []*schema.Column{LinkCategoriesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// LinkCategoriesColumns holds the columns for the "link_categories" table.
	LinkCategoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "name", Type: field.TypeString, Unique: true, Size: 20},
		{Name: "sort_order", Type: field.TypeInt, Default: 0},
	}
	// LinkCategoriesTable holds the schema information for the "link_categories" table.
	LinkCategoriesTable = &schema.Table{
		Name:       "link_categories",
		Columns:    LinkCategoriesColumns,
		PrimaryKey: []*schema.Column{LinkCategoriesColumns[0]},
	}
	// PostsColumns holds the columns for the "posts" table.
	PostsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "title", Type: field.TypeString, Size: 255},
		{Name: "summary", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "content", Type: field.TypeString, Size: 2147483647},
		{Name: "cover", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "read_time_minutes", Type: field.TypeUint},
		{Name: "view_count", Type: field.TypeUint, Default: 0},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"draft", "published", "archived"}, Default: "draft"},
		{Name: "published_at", Type: field.TypeTime, Nullable: true},
		{Name: "user_id", Type: field.TypeUint},
	}
	// PostsTable holds the schema information for the "posts" table.
	PostsTable = &schema.Table{
		Name:       "posts",
		Columns:    PostsColumns,
		PrimaryKey: []*schema.Column{PostsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "posts_users_posts",
				Columns:    []*schema.Column{PostsColumns[12]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// PostCategoriesColumns holds the columns for the "post_categories" table.
	PostCategoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "name", Type: field.TypeString, Unique: true, Size: 100},
		{Name: "slug", Type: field.TypeString, Unique: true, Size: 100},
	}
	// PostCategoriesTable holds the schema information for the "post_categories" table.
	PostCategoriesTable = &schema.Table{
		Name:       "post_categories",
		Columns:    PostCategoriesColumns,
		PrimaryKey: []*schema.Column{PostCategoriesColumns[0]},
	}
	// PostCategoryRelationsColumns holds the columns for the "post_category_relations" table.
	PostCategoryRelationsColumns = []*schema.Column{
		{Name: "post_id", Type: field.TypeUint},
		{Name: "post_category_id", Type: field.TypeUint},
	}
	// PostCategoryRelationsTable holds the schema information for the "post_category_relations" table.
	PostCategoryRelationsTable = &schema.Table{
		Name:       "post_category_relations",
		Columns:    PostCategoryRelationsColumns,
		PrimaryKey: []*schema.Column{PostCategoryRelationsColumns[0], PostCategoryRelationsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "post_category_relations_posts_post",
				Columns:    []*schema.Column{PostCategoryRelationsColumns[0]},
				RefColumns: []*schema.Column{PostsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "post_category_relations_post_categories_category",
				Columns:    []*schema.Column{PostCategoryRelationsColumns[1]},
				RefColumns: []*schema.Column{PostCategoriesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// PostTagsColumns holds the columns for the "post_tags" table.
	PostTagsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "name", Type: field.TypeString, Unique: true, Size: 100},
		{Name: "slug", Type: field.TypeString, Unique: true, Size: 100},
	}
	// PostTagsTable holds the schema information for the "post_tags" table.
	PostTagsTable = &schema.Table{
		Name:       "post_tags",
		Columns:    PostTagsColumns,
		PrimaryKey: []*schema.Column{PostTagsColumns[0]},
	}
	// PostTagRelationsColumns holds the columns for the "post_tag_relations" table.
	PostTagRelationsColumns = []*schema.Column{
		{Name: "post_id", Type: field.TypeUint},
		{Name: "post_tag_id", Type: field.TypeUint},
	}
	// PostTagRelationsTable holds the schema information for the "post_tag_relations" table.
	PostTagRelationsTable = &schema.Table{
		Name:       "post_tag_relations",
		Columns:    PostTagRelationsColumns,
		PrimaryKey: []*schema.Column{PostTagRelationsColumns[0], PostTagRelationsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "post_tag_relations_posts_post",
				Columns:    []*schema.Column{PostTagRelationsColumns[0]},
				RefColumns: []*schema.Column{PostsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "post_tag_relations_post_tags_tag",
				Columns:    []*schema.Column{PostTagRelationsColumns[1]},
				RefColumns: []*schema.Column{PostTagsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "uuid", Type: field.TypeUUID, Unique: true},
		{Name: "avatar", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "email", Type: field.TypeString, Unique: true, Size: 100},
		{Name: "password", Type: field.TypeString, Size: 255},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"reader", "admin"}, Default: "reader"},
		{Name: "username", Type: field.TypeString, Size: 50},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CommentsTable,
		LinksTable,
		LinkCategoriesTable,
		PostsTable,
		PostCategoriesTable,
		PostCategoryRelationsTable,
		PostTagsTable,
		PostTagRelationsTable,
		UsersTable,
	}
)

func init() {
	LinksTable.ForeignKeys[0].RefTable = LinkCategoriesTable
	PostsTable.ForeignKeys[0].RefTable = UsersTable
	PostCategoryRelationsTable.ForeignKeys[0].RefTable = PostsTable
	PostCategoryRelationsTable.ForeignKeys[1].RefTable = PostCategoriesTable
	PostCategoryRelationsTable.Annotation = &entsql.Annotation{
		Table: "post_category_relations",
	}
	PostTagRelationsTable.ForeignKeys[0].RefTable = PostsTable
	PostTagRelationsTable.ForeignKeys[1].RefTable = PostTagsTable
	PostTagRelationsTable.Annotation = &entsql.Annotation{
		Table: "post_tag_relations",
	}
}
