// Code generated by ent, DO NOT EDIT.

package ent

import (
	"blog-server/ent/link"
	"blog-server/ent/linkcategory"
	"blog-server/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LinkCategoryUpdate is the builder for updating LinkCategory entities.
type LinkCategoryUpdate struct {
	config
	hooks    []Hook
	mutation *LinkCategoryMutation
}

// Where appends a list predicates to the LinkCategoryUpdate builder.
func (_u *LinkCategoryUpdate) Where(ps ...predicate.LinkCategory) *LinkCategoryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *LinkCategoryUpdate) SetCreatedAt(v time.Time) *LinkCategoryUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *LinkCategoryUpdate) SetNillableCreatedAt(v *time.Time) *LinkCategoryUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LinkCategoryUpdate) SetUpdatedAt(v time.Time) *LinkCategoryUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *LinkCategoryUpdate) SetDeletedAt(v time.Time) *LinkCategoryUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *LinkCategoryUpdate) SetNillableDeletedAt(v *time.Time) *LinkCategoryUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *LinkCategoryUpdate) ClearDeletedAt() *LinkCategoryUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *LinkCategoryUpdate) SetName(v string) *LinkCategoryUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *LinkCategoryUpdate) SetNillableName(v *string) *LinkCategoryUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *LinkCategoryUpdate) SetSortOrder(v int) *LinkCategoryUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *LinkCategoryUpdate) SetNillableSortOrder(v *int) *LinkCategoryUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *LinkCategoryUpdate) AddSortOrder(v int) *LinkCategoryUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// AddLinkIDs adds the "links" edge to the Link entity by IDs.
func (_u *LinkCategoryUpdate) AddLinkIDs(ids ...uint) *LinkCategoryUpdate {
	_u.mutation.AddLinkIDs(ids...)
	return _u
}

// AddLinks adds the "links" edges to the Link entity.
func (_u *LinkCategoryUpdate) AddLinks(v ...*Link) *LinkCategoryUpdate {
	ids := make([]uint, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLinkIDs(ids...)
}

// Mutation returns the LinkCategoryMutation object of the builder.
func (_u *LinkCategoryUpdate) Mutation() *LinkCategoryMutation {
	return _u.mutation
}

// ClearLinks clears all "links" edges to the Link entity.
func (_u *LinkCategoryUpdate) ClearLinks() *LinkCategoryUpdate {
	_u.mutation.ClearLinks()
	return _u
}

// RemoveLinkIDs removes the "links" edge to Link entities by IDs.
func (_u *LinkCategoryUpdate) RemoveLinkIDs(ids ...uint) *LinkCategoryUpdate {
	_u.mutation.RemoveLinkIDs(ids...)
	return _u
}

// RemoveLinks removes "links" edges to Link entities.
func (_u *LinkCategoryUpdate) RemoveLinks(v ...*Link) *LinkCategoryUpdate {
	ids := make([]uint, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLinkIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LinkCategoryUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LinkCategoryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LinkCategoryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LinkCategoryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LinkCategoryUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if linkcategory.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized linkcategory.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := linkcategory.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *LinkCategoryUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := linkcategory.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "LinkCategory.name": %w`, err)}
		}
	}
	return nil
}

func (_u *LinkCategoryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(linkcategory.Table, linkcategory.Columns, sqlgraph.NewFieldSpec(linkcategory.FieldID, field.TypeUint))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(linkcategory.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(linkcategory.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(linkcategory.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(linkcategory.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(linkcategory.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(linkcategory.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(linkcategory.FieldSortOrder, field.TypeInt, value)
	}
	if _u.mutation.LinksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   linkcategory.LinksTable,
			Columns: []string{linkcategory.LinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(link.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLinksIDs(); len(nodes) > 0 && !_u.mutation.LinksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   linkcategory.LinksTable,
			Columns: []string{linkcategory.LinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(link.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LinksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   linkcategory.LinksTable,
			Columns: []string{linkcategory.LinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(link.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{linkcategory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LinkCategoryUpdateOne is the builder for updating a single LinkCategory entity.
type LinkCategoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LinkCategoryMutation
}

// SetCreatedAt sets the "created_at" field.
func (_u *LinkCategoryUpdateOne) SetCreatedAt(v time.Time) *LinkCategoryUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *LinkCategoryUpdateOne) SetNillableCreatedAt(v *time.Time) *LinkCategoryUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LinkCategoryUpdateOne) SetUpdatedAt(v time.Time) *LinkCategoryUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *LinkCategoryUpdateOne) SetDeletedAt(v time.Time) *LinkCategoryUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *LinkCategoryUpdateOne) SetNillableDeletedAt(v *time.Time) *LinkCategoryUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *LinkCategoryUpdateOne) ClearDeletedAt() *LinkCategoryUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *LinkCategoryUpdateOne) SetName(v string) *LinkCategoryUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *LinkCategoryUpdateOne) SetNillableName(v *string) *LinkCategoryUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *LinkCategoryUpdateOne) SetSortOrder(v int) *LinkCategoryUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *LinkCategoryUpdateOne) SetNillableSortOrder(v *int) *LinkCategoryUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *LinkCategoryUpdateOne) AddSortOrder(v int) *LinkCategoryUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// AddLinkIDs adds the "links" edge to the Link entity by IDs.
func (_u *LinkCategoryUpdateOne) AddLinkIDs(ids ...uint) *LinkCategoryUpdateOne {
	_u.mutation.AddLinkIDs(ids...)
	return _u
}

// AddLinks adds the "links" edges to the Link entity.
func (_u *LinkCategoryUpdateOne) AddLinks(v ...*Link) *LinkCategoryUpdateOne {
	ids := make([]uint, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLinkIDs(ids...)
}

// Mutation returns the LinkCategoryMutation object of the builder.
func (_u *LinkCategoryUpdateOne) Mutation() *LinkCategoryMutation {
	return _u.mutation
}

// ClearLinks clears all "links" edges to the Link entity.
func (_u *LinkCategoryUpdateOne) ClearLinks() *LinkCategoryUpdateOne {
	_u.mutation.ClearLinks()
	return _u
}

// RemoveLinkIDs removes the "links" edge to Link entities by IDs.
func (_u *LinkCategoryUpdateOne) RemoveLinkIDs(ids ...uint) *LinkCategoryUpdateOne {
	_u.mutation.RemoveLinkIDs(ids...)
	return _u
}

// RemoveLinks removes "links" edges to Link entities.
func (_u *LinkCategoryUpdateOne) RemoveLinks(v ...*Link) *LinkCategoryUpdateOne {
	ids := make([]uint, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLinkIDs(ids...)
}

// Where appends a list predicates to the LinkCategoryUpdate builder.
func (_u *LinkCategoryUpdateOne) Where(ps ...predicate.LinkCategory) *LinkCategoryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LinkCategoryUpdateOne) Select(field string, fields ...string) *LinkCategoryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LinkCategory entity.
func (_u *LinkCategoryUpdateOne) Save(ctx context.Context) (*LinkCategory, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LinkCategoryUpdateOne) SaveX(ctx context.Context) *LinkCategory {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LinkCategoryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LinkCategoryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LinkCategoryUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if linkcategory.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized linkcategory.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := linkcategory.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *LinkCategoryUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := linkcategory.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "LinkCategory.name": %w`, err)}
		}
	}
	return nil
}

func (_u *LinkCategoryUpdateOne) sqlSave(ctx context.Context) (_node *LinkCategory, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(linkcategory.Table, linkcategory.Columns, sqlgraph.NewFieldSpec(linkcategory.FieldID, field.TypeUint))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LinkCategory.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, linkcategory.FieldID)
		for _, f := range fields {
			if !linkcategory.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != linkcategory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(linkcategory.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(linkcategory.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(linkcategory.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(linkcategory.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(linkcategory.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(linkcategory.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(linkcategory.FieldSortOrder, field.TypeInt, value)
	}
	if _u.mutation.LinksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   linkcategory.LinksTable,
			Columns: []string{linkcategory.LinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(link.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLinksIDs(); len(nodes) > 0 && !_u.mutation.LinksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   linkcategory.LinksTable,
			Columns: []string{linkcategory.LinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(link.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LinksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   linkcategory.LinksTable,
			Columns: []string{linkcategory.LinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(link.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &LinkCategory{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{linkcategory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
