// Code generated by ent, DO NOT EDIT.

package ent

import (
	"blog-server/ent/link"
	"blog-server/ent/linkcategory"
	"blog-server/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LinkUpdate is the builder for updating Link entities.
type LinkUpdate struct {
	config
	hooks    []Hook
	mutation *LinkMutation
}

// Where appends a list predicates to the LinkUpdate builder.
func (_u *LinkUpdate) Where(ps ...predicate.Link) *LinkUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *LinkUpdate) SetCreatedAt(v time.Time) *LinkUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *LinkUpdate) SetNillableCreatedAt(v *time.Time) *LinkUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LinkUpdate) SetUpdatedAt(v time.Time) *LinkUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *LinkUpdate) SetDeletedAt(v time.Time) *LinkUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *LinkUpdate) SetNillableDeletedAt(v *time.Time) *LinkUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *LinkUpdate) ClearDeletedAt() *LinkUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetDescription sets the "description" field.
func (_u *LinkUpdate) SetDescription(v string) *LinkUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *LinkUpdate) SetNillableDescription(v *string) *LinkUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *LinkUpdate) ClearDescription() *LinkUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *LinkUpdate) SetEnabled(v bool) *LinkUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *LinkUpdate) SetNillableEnabled(v *bool) *LinkUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *LinkUpdate) SetName(v string) *LinkUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *LinkUpdate) SetNillableName(v *string) *LinkUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *LinkUpdate) SetSortOrder(v int) *LinkUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *LinkUpdate) SetNillableSortOrder(v *int) *LinkUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *LinkUpdate) AddSortOrder(v int) *LinkUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetURL sets the "url" field.
func (_u *LinkUpdate) SetURL(v string) *LinkUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *LinkUpdate) SetNillableURL(v *string) *LinkUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetAvatar sets the "avatar" field.
func (_u *LinkUpdate) SetAvatar(v string) *LinkUpdate {
	_u.mutation.SetAvatar(v)
	return _u
}

// SetNillableAvatar sets the "avatar" field if the given value is not nil.
func (_u *LinkUpdate) SetNillableAvatar(v *string) *LinkUpdate {
	if v != nil {
		_u.SetAvatar(*v)
	}
	return _u
}

// ClearAvatar clears the value of the "avatar" field.
func (_u *LinkUpdate) ClearAvatar() *LinkUpdate {
	_u.mutation.ClearAvatar()
	return _u
}

// SetStatus sets the "status" field.
func (_u *LinkUpdate) SetStatus(v link.Status) *LinkUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *LinkUpdate) SetNillableStatus(v *link.Status) *LinkUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCategoryID sets the "category_id" field.
func (_u *LinkUpdate) SetCategoryID(v uint) *LinkUpdate {
	_u.mutation.SetCategoryID(v)
	return _u
}

// SetNillableCategoryID sets the "category_id" field if the given value is not nil.
func (_u *LinkUpdate) SetNillableCategoryID(v *uint) *LinkUpdate {
	if v != nil {
		_u.SetCategoryID(*v)
	}
	return _u
}

// ClearCategoryID clears the value of the "category_id" field.
func (_u *LinkUpdate) ClearCategoryID() *LinkUpdate {
	_u.mutation.ClearCategoryID()
	return _u
}

// SetCategory sets the "category" edge to the LinkCategory entity.
func (_u *LinkUpdate) SetCategory(v *LinkCategory) *LinkUpdate {
	return _u.SetCategoryID(v.ID)
}

// Mutation returns the LinkMutation object of the builder.
func (_u *LinkUpdate) Mutation() *LinkMutation {
	return _u.mutation
}

// ClearCategory clears the "category" edge to the LinkCategory entity.
func (_u *LinkUpdate) ClearCategory() *LinkUpdate {
	_u.mutation.ClearCategory()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LinkUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LinkUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LinkUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LinkUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LinkUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if link.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized link.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := link.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *LinkUpdate) check() error {
	if v, ok := _u.mutation.Description(); ok {
		if err := link.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Link.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := link.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Link.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.URL(); ok {
		if err := link.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Link.url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Avatar(); ok {
		if err := link.AvatarValidator(v); err != nil {
			return &ValidationError{Name: "avatar", err: fmt.Errorf(`ent: validator failed for field "Link.avatar": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := link.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Link.status": %w`, err)}
		}
	}
	return nil
}

func (_u *LinkUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(link.Table, link.Columns, sqlgraph.NewFieldSpec(link.FieldID, field.TypeUint))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(link.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(link.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(link.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(link.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(link.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(link.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(link.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(link.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(link.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(link.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(link.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Avatar(); ok {
		_spec.SetField(link.FieldAvatar, field.TypeString, value)
	}
	if _u.mutation.AvatarCleared() {
		_spec.ClearField(link.FieldAvatar, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(link.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.CategoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   link.CategoryTable,
			Columns: []string{link.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(linkcategory.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   link.CategoryTable,
			Columns: []string{link.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(linkcategory.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{link.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LinkUpdateOne is the builder for updating a single Link entity.
type LinkUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LinkMutation
}

// SetCreatedAt sets the "created_at" field.
func (_u *LinkUpdateOne) SetCreatedAt(v time.Time) *LinkUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *LinkUpdateOne) SetNillableCreatedAt(v *time.Time) *LinkUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LinkUpdateOne) SetUpdatedAt(v time.Time) *LinkUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *LinkUpdateOne) SetDeletedAt(v time.Time) *LinkUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *LinkUpdateOne) SetNillableDeletedAt(v *time.Time) *LinkUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *LinkUpdateOne) ClearDeletedAt() *LinkUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetDescription sets the "description" field.
func (_u *LinkUpdateOne) SetDescription(v string) *LinkUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *LinkUpdateOne) SetNillableDescription(v *string) *LinkUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *LinkUpdateOne) ClearDescription() *LinkUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *LinkUpdateOne) SetEnabled(v bool) *LinkUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *LinkUpdateOne) SetNillableEnabled(v *bool) *LinkUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *LinkUpdateOne) SetName(v string) *LinkUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *LinkUpdateOne) SetNillableName(v *string) *LinkUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *LinkUpdateOne) SetSortOrder(v int) *LinkUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *LinkUpdateOne) SetNillableSortOrder(v *int) *LinkUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *LinkUpdateOne) AddSortOrder(v int) *LinkUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetURL sets the "url" field.
func (_u *LinkUpdateOne) SetURL(v string) *LinkUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *LinkUpdateOne) SetNillableURL(v *string) *LinkUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetAvatar sets the "avatar" field.
func (_u *LinkUpdateOne) SetAvatar(v string) *LinkUpdateOne {
	_u.mutation.SetAvatar(v)
	return _u
}

// SetNillableAvatar sets the "avatar" field if the given value is not nil.
func (_u *LinkUpdateOne) SetNillableAvatar(v *string) *LinkUpdateOne {
	if v != nil {
		_u.SetAvatar(*v)
	}
	return _u
}

// ClearAvatar clears the value of the "avatar" field.
func (_u *LinkUpdateOne) ClearAvatar() *LinkUpdateOne {
	_u.mutation.ClearAvatar()
	return _u
}

// SetStatus sets the "status" field.
func (_u *LinkUpdateOne) SetStatus(v link.Status) *LinkUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *LinkUpdateOne) SetNillableStatus(v *link.Status) *LinkUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCategoryID sets the "category_id" field.
func (_u *LinkUpdateOne) SetCategoryID(v uint) *LinkUpdateOne {
	_u.mutation.SetCategoryID(v)
	return _u
}

// SetNillableCategoryID sets the "category_id" field if the given value is not nil.
func (_u *LinkUpdateOne) SetNillableCategoryID(v *uint) *LinkUpdateOne {
	if v != nil {
		_u.SetCategoryID(*v)
	}
	return _u
}

// ClearCategoryID clears the value of the "category_id" field.
func (_u *LinkUpdateOne) ClearCategoryID() *LinkUpdateOne {
	_u.mutation.ClearCategoryID()
	return _u
}

// SetCategory sets the "category" edge to the LinkCategory entity.
func (_u *LinkUpdateOne) SetCategory(v *LinkCategory) *LinkUpdateOne {
	return _u.SetCategoryID(v.ID)
}

// Mutation returns the LinkMutation object of the builder.
func (_u *LinkUpdateOne) Mutation() *LinkMutation {
	return _u.mutation
}

// ClearCategory clears the "category" edge to the LinkCategory entity.
func (_u *LinkUpdateOne) ClearCategory() *LinkUpdateOne {
	_u.mutation.ClearCategory()
	return _u
}

// Where appends a list predicates to the LinkUpdate builder.
func (_u *LinkUpdateOne) Where(ps ...predicate.Link) *LinkUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LinkUpdateOne) Select(field string, fields ...string) *LinkUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Link entity.
func (_u *LinkUpdateOne) Save(ctx context.Context) (*Link, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LinkUpdateOne) SaveX(ctx context.Context) *Link {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LinkUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LinkUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LinkUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if link.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized link.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := link.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *LinkUpdateOne) check() error {
	if v, ok := _u.mutation.Description(); ok {
		if err := link.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Link.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := link.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Link.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.URL(); ok {
		if err := link.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Link.url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Avatar(); ok {
		if err := link.AvatarValidator(v); err != nil {
			return &ValidationError{Name: "avatar", err: fmt.Errorf(`ent: validator failed for field "Link.avatar": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := link.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Link.status": %w`, err)}
		}
	}
	return nil
}

func (_u *LinkUpdateOne) sqlSave(ctx context.Context) (_node *Link, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(link.Table, link.Columns, sqlgraph.NewFieldSpec(link.FieldID, field.TypeUint))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Link.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, link.FieldID)
		for _, f := range fields {
			if !link.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != link.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(link.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(link.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(link.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(link.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(link.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(link.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(link.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(link.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(link.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(link.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(link.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Avatar(); ok {
		_spec.SetField(link.FieldAvatar, field.TypeString, value)
	}
	if _u.mutation.AvatarCleared() {
		_spec.ClearField(link.FieldAvatar, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(link.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.CategoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   link.CategoryTable,
			Columns: []string{link.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(linkcategory.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   link.CategoryTable,
			Columns: []string{link.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(linkcategory.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Link{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{link.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
