// Code generated by ent, DO NOT EDIT.

package ent

import (
	"blog-server/ent/link"
	"blog-server/ent/linkcategory"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LinkCreate is the builder for creating a Link entity.
type LinkCreate struct {
	config
	mutation *LinkMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *LinkCreate) SetCreatedAt(v time.Time) *LinkCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LinkCreate) SetNillableCreatedAt(v *time.Time) *LinkCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *LinkCreate) SetUpdatedAt(v time.Time) *LinkCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *LinkCreate) SetNillableUpdatedAt(v *time.Time) *LinkCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *LinkCreate) SetDeletedAt(v time.Time) *LinkCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *LinkCreate) SetNillableDeletedAt(v *time.Time) *LinkCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *LinkCreate) SetDescription(v string) *LinkCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *LinkCreate) SetNillableDescription(v *string) *LinkCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *LinkCreate) SetEnabled(v bool) *LinkCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *LinkCreate) SetNillableEnabled(v *bool) *LinkCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *LinkCreate) SetName(v string) *LinkCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *LinkCreate) SetSortOrder(v int) *LinkCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *LinkCreate) SetNillableSortOrder(v *int) *LinkCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetURL sets the "url" field.
func (_c *LinkCreate) SetURL(v string) *LinkCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetAvatar sets the "avatar" field.
func (_c *LinkCreate) SetAvatar(v string) *LinkCreate {
	_c.mutation.SetAvatar(v)
	return _c
}

// SetNillableAvatar sets the "avatar" field if the given value is not nil.
func (_c *LinkCreate) SetNillableAvatar(v *string) *LinkCreate {
	if v != nil {
		_c.SetAvatar(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *LinkCreate) SetStatus(v link.Status) *LinkCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *LinkCreate) SetNillableStatus(v *link.Status) *LinkCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCategoryID sets the "category_id" field.
func (_c *LinkCreate) SetCategoryID(v uint) *LinkCreate {
	_c.mutation.SetCategoryID(v)
	return _c
}

// SetNillableCategoryID sets the "category_id" field if the given value is not nil.
func (_c *LinkCreate) SetNillableCategoryID(v *uint) *LinkCreate {
	if v != nil {
		_c.SetCategoryID(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *LinkCreate) SetID(v uint) *LinkCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetCategory sets the "category" edge to the LinkCategory entity.
func (_c *LinkCreate) SetCategory(v *LinkCategory) *LinkCreate {
	return _c.SetCategoryID(v.ID)
}

// Mutation returns the LinkMutation object of the builder.
func (_c *LinkCreate) Mutation() *LinkMutation {
	return _c.mutation
}

// Save creates the Link in the database.
func (_c *LinkCreate) Save(ctx context.Context) (*Link, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LinkCreate) SaveX(ctx context.Context) *Link {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LinkCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LinkCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LinkCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if link.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized link.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := link.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if link.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized link.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := link.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := link.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := link.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := link.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *LinkCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Link.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Link.updated_at"`)}
	}
	if v, ok := _c.mutation.Description(); ok {
		if err := link.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Link.description": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "Link.enabled"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Link.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := link.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Link.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "Link.sort_order"`)}
	}
	if _, ok := _c.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "Link.url"`)}
	}
	if v, ok := _c.mutation.URL(); ok {
		if err := link.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Link.url": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Avatar(); ok {
		if err := link.AvatarValidator(v); err != nil {
			return &ValidationError{Name: "avatar", err: fmt.Errorf(`ent: validator failed for field "Link.avatar": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Link.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := link.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Link.status": %w`, err)}
		}
	}
	return nil
}

func (_c *LinkCreate) sqlSave(ctx context.Context) (*Link, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LinkCreate) createSpec() (*Link, *sqlgraph.CreateSpec) {
	var (
		_node = &Link{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(link.Table, sqlgraph.NewFieldSpec(link.FieldID, field.TypeUint))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(link.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(link.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(link.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(link.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(link.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(link.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(link.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(link.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.Avatar(); ok {
		_spec.SetField(link.FieldAvatar, field.TypeString, value)
		_node.Avatar = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(link.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if nodes := _c.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   link.CategoryTable,
			Columns: []string{link.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(linkcategory.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CategoryID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// LinkCreateBulk is the builder for creating many Link entities in bulk.
type LinkCreateBulk struct {
	config
	err      error
	builders []*LinkCreate
}

// Save creates the Link entities in the database.
func (_c *LinkCreateBulk) Save(ctx context.Context) ([]*Link, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Link, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LinkMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LinkCreateBulk) SaveX(ctx context.Context) []*Link {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LinkCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LinkCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
