// Code generated by ent, DO NOT EDIT.

package ent

import (
	"blog-server/ent/link"
	"blog-server/ent/linkcategory"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LinkCategoryCreate is the builder for creating a LinkCategory entity.
type LinkCategoryCreate struct {
	config
	mutation *LinkCategoryMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *LinkCategoryCreate) SetCreatedAt(v time.Time) *LinkCategoryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LinkCategoryCreate) SetNillableCreatedAt(v *time.Time) *LinkCategoryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *LinkCategoryCreate) SetUpdatedAt(v time.Time) *LinkCategoryCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *LinkCategoryCreate) SetNillableUpdatedAt(v *time.Time) *LinkCategoryCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *LinkCategoryCreate) SetDeletedAt(v time.Time) *LinkCategoryCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *LinkCategoryCreate) SetNillableDeletedAt(v *time.Time) *LinkCategoryCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *LinkCategoryCreate) SetName(v string) *LinkCategoryCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *LinkCategoryCreate) SetSortOrder(v int) *LinkCategoryCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *LinkCategoryCreate) SetNillableSortOrder(v *int) *LinkCategoryCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *LinkCategoryCreate) SetID(v uint) *LinkCategoryCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddLinkIDs adds the "links" edge to the Link entity by IDs.
func (_c *LinkCategoryCreate) AddLinkIDs(ids ...uint) *LinkCategoryCreate {
	_c.mutation.AddLinkIDs(ids...)
	return _c
}

// AddLinks adds the "links" edges to the Link entity.
func (_c *LinkCategoryCreate) AddLinks(v ...*Link) *LinkCategoryCreate {
	ids := make([]uint, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddLinkIDs(ids...)
}

// Mutation returns the LinkCategoryMutation object of the builder.
func (_c *LinkCategoryCreate) Mutation() *LinkCategoryMutation {
	return _c.mutation
}

// Save creates the LinkCategory in the database.
func (_c *LinkCategoryCreate) Save(ctx context.Context) (*LinkCategory, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LinkCategoryCreate) SaveX(ctx context.Context) *LinkCategory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LinkCategoryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LinkCategoryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LinkCategoryCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if linkcategory.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized linkcategory.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := linkcategory.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if linkcategory.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized linkcategory.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := linkcategory.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := linkcategory.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *LinkCategoryCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "LinkCategory.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "LinkCategory.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "LinkCategory.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := linkcategory.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "LinkCategory.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "LinkCategory.sort_order"`)}
	}
	return nil
}

func (_c *LinkCategoryCreate) sqlSave(ctx context.Context) (*LinkCategory, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LinkCategoryCreate) createSpec() (*LinkCategory, *sqlgraph.CreateSpec) {
	var (
		_node = &LinkCategory{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(linkcategory.Table, sqlgraph.NewFieldSpec(linkcategory.FieldID, field.TypeUint))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(linkcategory.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(linkcategory.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(linkcategory.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(linkcategory.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(linkcategory.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if nodes := _c.mutation.LinksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   linkcategory.LinksTable,
			Columns: []string{linkcategory.LinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(link.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// LinkCategoryCreateBulk is the builder for creating many LinkCategory entities in bulk.
type LinkCategoryCreateBulk struct {
	config
	err      error
	builders []*LinkCategoryCreate
}

// Save creates the LinkCategory entities in the database.
func (_c *LinkCategoryCreateBulk) Save(ctx context.Context) ([]*LinkCategory, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LinkCategory, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LinkCategoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LinkCategoryCreateBulk) SaveX(ctx context.Context) []*LinkCategory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LinkCategoryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LinkCategoryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
