// Code generated by ent, DO NOT EDIT.

package ent

import (
	"blog-server/ent/postcategoryrelation"
	"blog-server/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// PostCategoryRelationDelete is the builder for deleting a PostCategoryRelation entity.
type PostCategoryRelationDelete struct {
	config
	hooks    []Hook
	mutation *PostCategoryRelationMutation
}

// Where appends a list predicates to the PostCategoryRelationDelete builder.
func (_d *PostCategoryRelationDelete) Where(ps ...predicate.PostCategoryRelation) *PostCategoryRelationDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *PostCategoryRelationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PostCategoryRelationDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *PostCategoryRelationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(postcategoryrelation.Table, nil)
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// PostCategoryRelationDeleteOne is the builder for deleting a single PostCategoryRelation entity.
type PostCategoryRelationDeleteOne struct {
	_d *PostCategoryRelationDelete
}

// Where appends a list predicates to the PostCategoryRelationDelete builder.
func (_d *PostCategoryRelationDeleteOne) Where(ps ...predicate.PostCategoryRelation) *PostCategoryRelationDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *PostCategoryRelationDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{postcategoryrelation.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PostCategoryRelationDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
