// Code generated by ent, DO NOT EDIT.

package ent

import (
	"blog-server/ent/posttagrelation"
	"blog-server/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// PostTagRelationDelete is the builder for deleting a PostTagRelation entity.
type PostTagRelationDelete struct {
	config
	hooks    []Hook
	mutation *PostTagRelationMutation
}

// Where appends a list predicates to the PostTagRelationDelete builder.
func (_d *PostTagRelationDelete) Where(ps ...predicate.PostTagRelation) *PostTagRelationDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *PostTagRelationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PostTagRelationDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *PostTagRelationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(posttagrelation.Table, nil)
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// PostTagRelationDeleteOne is the builder for deleting a single PostTagRelation entity.
type PostTagRelationDeleteOne struct {
	_d *PostTagRelationDelete
}

// Where appends a list predicates to the PostTagRelationDelete builder.
func (_d *PostTagRelationDeleteOne) Where(ps ...predicate.PostTagRelation) *PostTagRelationDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *PostTagRelationDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{posttagrelation.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PostTagRelationDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
