// Code generated by ent, DO NOT EDIT.

package ent

import (
	"blog-server/ent/post"
	"blog-server/ent/posttag"
	"blog-server/ent/posttagrelation"
	"blog-server/ent/predicate"
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// PostTagRelationQuery is the builder for querying PostTagRelation entities.
type PostTagRelationQuery struct {
	config
	ctx        *QueryContext
	order      []posttagrelation.OrderOption
	inters     []Interceptor
	predicates []predicate.PostTagRelation
	withPost   *PostQuery
	withTag    *PostTagQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PostTagRelationQuery builder.
func (_q *PostTagRelationQuery) Where(ps ...predicate.PostTagRelation) *PostTagRelationQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *PostTagRelationQuery) Limit(limit int) *PostTagRelationQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *PostTagRelationQuery) Offset(offset int) *PostTagRelationQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *PostTagRelationQuery) Unique(unique bool) *PostTagRelationQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *PostTagRelationQuery) Order(o ...posttagrelation.OrderOption) *PostTagRelationQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryPost chains the current query on the "post" edge.
func (_q *PostTagRelationQuery) QueryPost() *PostQuery {
	query := (&PostClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(posttagrelation.Table, posttagrelation.PostColumn, selector),
			sqlgraph.To(post.Table, post.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, posttagrelation.PostTable, posttagrelation.PostColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTag chains the current query on the "tag" edge.
func (_q *PostTagRelationQuery) QueryTag() *PostTagQuery {
	query := (&PostTagClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(posttagrelation.Table, posttagrelation.TagColumn, selector),
			sqlgraph.To(posttag.Table, posttag.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, posttagrelation.TagTable, posttagrelation.TagColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PostTagRelation entity from the query.
// Returns a *NotFoundError when no PostTagRelation was found.
func (_q *PostTagRelationQuery) First(ctx context.Context) (*PostTagRelation, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{posttagrelation.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *PostTagRelationQuery) FirstX(ctx context.Context) *PostTagRelation {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// Only returns a single PostTagRelation entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PostTagRelation entity is found.
// Returns a *NotFoundError when no PostTagRelation entities are found.
func (_q *PostTagRelationQuery) Only(ctx context.Context) (*PostTagRelation, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{posttagrelation.Label}
	default:
		return nil, &NotSingularError{posttagrelation.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *PostTagRelationQuery) OnlyX(ctx context.Context) *PostTagRelation {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// All executes the query and returns a list of PostTagRelations.
func (_q *PostTagRelationQuery) All(ctx context.Context) ([]*PostTagRelation, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PostTagRelation, *PostTagRelationQuery]()
	return withInterceptors[[]*PostTagRelation](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *PostTagRelationQuery) AllX(ctx context.Context) []*PostTagRelation {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// Count returns the count of the given query.
func (_q *PostTagRelationQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*PostTagRelationQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *PostTagRelationQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *PostTagRelationQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.First(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *PostTagRelationQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PostTagRelationQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *PostTagRelationQuery) Clone() *PostTagRelationQuery {
	if _q == nil {
		return nil
	}
	return &PostTagRelationQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]posttagrelation.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.PostTagRelation{}, _q.predicates...),
		withPost:   _q.withPost.Clone(),
		withTag:    _q.withTag.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithPost tells the query-builder to eager-load the nodes that are connected to
// the "post" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PostTagRelationQuery) WithPost(opts ...func(*PostQuery)) *PostTagRelationQuery {
	query := (&PostClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPost = query
	return _q
}

// WithTag tells the query-builder to eager-load the nodes that are connected to
// the "tag" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PostTagRelationQuery) WithTag(opts ...func(*PostTagQuery)) *PostTagRelationQuery {
	query := (&PostTagClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTag = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		PostID uint `json:"post_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PostTagRelation.Query().
//		GroupBy(posttagrelation.FieldPostID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *PostTagRelationQuery) GroupBy(field string, fields ...string) *PostTagRelationGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PostTagRelationGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = posttagrelation.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		PostID uint `json:"post_id,omitempty"`
//	}
//
//	client.PostTagRelation.Query().
//		Select(posttagrelation.FieldPostID).
//		Scan(ctx, &v)
func (_q *PostTagRelationQuery) Select(fields ...string) *PostTagRelationSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &PostTagRelationSelect{PostTagRelationQuery: _q}
	sbuild.label = posttagrelation.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PostTagRelationSelect configured with the given aggregations.
func (_q *PostTagRelationQuery) Aggregate(fns ...AggregateFunc) *PostTagRelationSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *PostTagRelationQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !posttagrelation.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *PostTagRelationQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PostTagRelation, error) {
	var (
		nodes       = []*PostTagRelation{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withPost != nil,
			_q.withTag != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PostTagRelation).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PostTagRelation{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withPost; query != nil {
		if err := _q.loadPost(ctx, query, nodes, nil,
			func(n *PostTagRelation, e *Post) { n.Edges.Post = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withTag; query != nil {
		if err := _q.loadTag(ctx, query, nodes, nil,
			func(n *PostTagRelation, e *PostTag) { n.Edges.Tag = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *PostTagRelationQuery) loadPost(ctx context.Context, query *PostQuery, nodes []*PostTagRelation, init func(*PostTagRelation), assign func(*PostTagRelation, *Post)) error {
	ids := make([]uint, 0, len(nodes))
	nodeids := make(map[uint][]*PostTagRelation)
	for i := range nodes {
		fk := nodes[i].PostID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(post.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "post_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *PostTagRelationQuery) loadTag(ctx context.Context, query *PostTagQuery, nodes []*PostTagRelation, init func(*PostTagRelation), assign func(*PostTagRelation, *PostTag)) error {
	ids := make([]uint, 0, len(nodes))
	nodeids := make(map[uint][]*PostTagRelation)
	for i := range nodes {
		fk := nodes[i].PostTagID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(posttag.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "post_tag_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *PostTagRelationQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Unique = false
	_spec.Node.Columns = nil
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *PostTagRelationQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(posttagrelation.Table, posttagrelation.Columns, nil)
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		for i := range fields {
			_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
		}
		if _q.withPost != nil {
			_spec.Node.AddColumnOnce(posttagrelation.FieldPostID)
		}
		if _q.withTag != nil {
			_spec.Node.AddColumnOnce(posttagrelation.FieldPostTagID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *PostTagRelationQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(posttagrelation.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = posttagrelation.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PostTagRelationGroupBy is the group-by builder for PostTagRelation entities.
type PostTagRelationGroupBy struct {
	selector
	build *PostTagRelationQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *PostTagRelationGroupBy) Aggregate(fns ...AggregateFunc) *PostTagRelationGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *PostTagRelationGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PostTagRelationQuery, *PostTagRelationGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *PostTagRelationGroupBy) sqlScan(ctx context.Context, root *PostTagRelationQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PostTagRelationSelect is the builder for selecting fields of PostTagRelation entities.
type PostTagRelationSelect struct {
	*PostTagRelationQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *PostTagRelationSelect) Aggregate(fns ...AggregateFunc) *PostTagRelationSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *PostTagRelationSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PostTagRelationQuery, *PostTagRelationSelect](ctx, _s.PostTagRelationQuery, _s, _s.inters, v)
}

func (_s *PostTagRelationSelect) sqlScan(ctx context.Context, root *PostTagRelationQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
