// Code generated by ent, DO NOT EDIT.

package ent

import (
	"blog-server/ent/post"
	"blog-server/ent/postcategory"
	"blog-server/ent/postcategoryrelation"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// PostCategoryRelation is the model entity for the PostCategoryRelation schema.
type PostCategoryRelation struct {
	config `json:"-"`
	// PostID holds the value of the "post_id" field.
	PostID uint `json:"post_id,omitempty"`
	// PostCategoryID holds the value of the "post_category_id" field.
	PostCategoryID uint `json:"post_category_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PostCategoryRelationQuery when eager-loading is set.
	Edges        PostCategoryRelationEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PostCategoryRelationEdges holds the relations/edges for other nodes in the graph.
type PostCategoryRelationEdges struct {
	// Post holds the value of the post edge.
	Post *Post `json:"post,omitempty"`
	// Category holds the value of the category edge.
	Category *PostCategory `json:"category,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// PostOrErr returns the Post value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PostCategoryRelationEdges) PostOrErr() (*Post, error) {
	if e.Post != nil {
		return e.Post, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: post.Label}
	}
	return nil, &NotLoadedError{edge: "post"}
}

// CategoryOrErr returns the Category value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PostCategoryRelationEdges) CategoryOrErr() (*PostCategory, error) {
	if e.Category != nil {
		return e.Category, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: postcategory.Label}
	}
	return nil, &NotLoadedError{edge: "category"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PostCategoryRelation) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case postcategoryrelation.FieldPostID, postcategoryrelation.FieldPostCategoryID:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PostCategoryRelation fields.
func (_m *PostCategoryRelation) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case postcategoryrelation.FieldPostID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field post_id", values[i])
			} else if value.Valid {
				_m.PostID = uint(value.Int64)
			}
		case postcategoryrelation.FieldPostCategoryID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field post_category_id", values[i])
			} else if value.Valid {
				_m.PostCategoryID = uint(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PostCategoryRelation.
// This includes values selected through modifiers, order, etc.
func (_m *PostCategoryRelation) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPost queries the "post" edge of the PostCategoryRelation entity.
func (_m *PostCategoryRelation) QueryPost() *PostQuery {
	return NewPostCategoryRelationClient(_m.config).QueryPost(_m)
}

// QueryCategory queries the "category" edge of the PostCategoryRelation entity.
func (_m *PostCategoryRelation) QueryCategory() *PostCategoryQuery {
	return NewPostCategoryRelationClient(_m.config).QueryCategory(_m)
}

// Update returns a builder for updating this PostCategoryRelation.
// Note that you need to call PostCategoryRelation.Unwrap() before calling this method if this PostCategoryRelation
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PostCategoryRelation) Update() *PostCategoryRelationUpdateOne {
	return NewPostCategoryRelationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PostCategoryRelation entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PostCategoryRelation) Unwrap() *PostCategoryRelation {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PostCategoryRelation is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PostCategoryRelation) String() string {
	var builder strings.Builder
	builder.WriteString("PostCategoryRelation(")
	builder.WriteString("post_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PostID))
	builder.WriteString(", ")
	builder.WriteString("post_category_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PostCategoryID))
	builder.WriteByte(')')
	return builder.String()
}

// PostCategoryRelations is a parsable slice of PostCategoryRelation.
type PostCategoryRelations []*PostCategoryRelation
