// Code generated by ent, DO NOT EDIT.

package ent

import (
	"blog-server/ent/post"
	"blog-server/ent/posttag"
	"blog-server/ent/posttagrelation"
	"blog-server/ent/predicate"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PostTagRelationUpdate is the builder for updating PostTagRelation entities.
type PostTagRelationUpdate struct {
	config
	hooks    []Hook
	mutation *PostTagRelationMutation
}

// Where appends a list predicates to the PostTagRelationUpdate builder.
func (_u *PostTagRelationUpdate) Where(ps ...predicate.PostTagRelation) *PostTagRelationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPostID sets the "post_id" field.
func (_u *PostTagRelationUpdate) SetPostID(v uint) *PostTagRelationUpdate {
	_u.mutation.SetPostID(v)
	return _u
}

// SetNillablePostID sets the "post_id" field if the given value is not nil.
func (_u *PostTagRelationUpdate) SetNillablePostID(v *uint) *PostTagRelationUpdate {
	if v != nil {
		_u.SetPostID(*v)
	}
	return _u
}

// SetPostTagID sets the "post_tag_id" field.
func (_u *PostTagRelationUpdate) SetPostTagID(v uint) *PostTagRelationUpdate {
	_u.mutation.SetPostTagID(v)
	return _u
}

// SetNillablePostTagID sets the "post_tag_id" field if the given value is not nil.
func (_u *PostTagRelationUpdate) SetNillablePostTagID(v *uint) *PostTagRelationUpdate {
	if v != nil {
		_u.SetPostTagID(*v)
	}
	return _u
}

// SetPost sets the "post" edge to the Post entity.
func (_u *PostTagRelationUpdate) SetPost(v *Post) *PostTagRelationUpdate {
	return _u.SetPostID(v.ID)
}

// SetTagID sets the "tag" edge to the PostTag entity by ID.
func (_u *PostTagRelationUpdate) SetTagID(id uint) *PostTagRelationUpdate {
	_u.mutation.SetTagID(id)
	return _u
}

// SetTag sets the "tag" edge to the PostTag entity.
func (_u *PostTagRelationUpdate) SetTag(v *PostTag) *PostTagRelationUpdate {
	return _u.SetTagID(v.ID)
}

// Mutation returns the PostTagRelationMutation object of the builder.
func (_u *PostTagRelationUpdate) Mutation() *PostTagRelationMutation {
	return _u.mutation
}

// ClearPost clears the "post" edge to the Post entity.
func (_u *PostTagRelationUpdate) ClearPost() *PostTagRelationUpdate {
	_u.mutation.ClearPost()
	return _u
}

// ClearTag clears the "tag" edge to the PostTag entity.
func (_u *PostTagRelationUpdate) ClearTag() *PostTagRelationUpdate {
	_u.mutation.ClearTag()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PostTagRelationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PostTagRelationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PostTagRelationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PostTagRelationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PostTagRelationUpdate) check() error {
	if _u.mutation.PostCleared() && len(_u.mutation.PostIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PostTagRelation.post"`)
	}
	if _u.mutation.TagCleared() && len(_u.mutation.TagIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PostTagRelation.tag"`)
	}
	return nil
}

func (_u *PostTagRelationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(posttagrelation.Table, posttagrelation.Columns, sqlgraph.NewFieldSpec(posttagrelation.FieldPostID, field.TypeUint), sqlgraph.NewFieldSpec(posttagrelation.FieldPostTagID, field.TypeUint))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.PostCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   posttagrelation.PostTable,
			Columns: []string{posttagrelation.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   posttagrelation.PostTable,
			Columns: []string{posttagrelation.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TagCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   posttagrelation.TagTable,
			Columns: []string{posttagrelation.TagColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(posttag.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TagIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   posttagrelation.TagTable,
			Columns: []string{posttagrelation.TagColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(posttag.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{posttagrelation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PostTagRelationUpdateOne is the builder for updating a single PostTagRelation entity.
type PostTagRelationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PostTagRelationMutation
}

// SetPostID sets the "post_id" field.
func (_u *PostTagRelationUpdateOne) SetPostID(v uint) *PostTagRelationUpdateOne {
	_u.mutation.SetPostID(v)
	return _u
}

// SetNillablePostID sets the "post_id" field if the given value is not nil.
func (_u *PostTagRelationUpdateOne) SetNillablePostID(v *uint) *PostTagRelationUpdateOne {
	if v != nil {
		_u.SetPostID(*v)
	}
	return _u
}

// SetPostTagID sets the "post_tag_id" field.
func (_u *PostTagRelationUpdateOne) SetPostTagID(v uint) *PostTagRelationUpdateOne {
	_u.mutation.SetPostTagID(v)
	return _u
}

// SetNillablePostTagID sets the "post_tag_id" field if the given value is not nil.
func (_u *PostTagRelationUpdateOne) SetNillablePostTagID(v *uint) *PostTagRelationUpdateOne {
	if v != nil {
		_u.SetPostTagID(*v)
	}
	return _u
}

// SetPost sets the "post" edge to the Post entity.
func (_u *PostTagRelationUpdateOne) SetPost(v *Post) *PostTagRelationUpdateOne {
	return _u.SetPostID(v.ID)
}

// SetTagID sets the "tag" edge to the PostTag entity by ID.
func (_u *PostTagRelationUpdateOne) SetTagID(id uint) *PostTagRelationUpdateOne {
	_u.mutation.SetTagID(id)
	return _u
}

// SetTag sets the "tag" edge to the PostTag entity.
func (_u *PostTagRelationUpdateOne) SetTag(v *PostTag) *PostTagRelationUpdateOne {
	return _u.SetTagID(v.ID)
}

// Mutation returns the PostTagRelationMutation object of the builder.
func (_u *PostTagRelationUpdateOne) Mutation() *PostTagRelationMutation {
	return _u.mutation
}

// ClearPost clears the "post" edge to the Post entity.
func (_u *PostTagRelationUpdateOne) ClearPost() *PostTagRelationUpdateOne {
	_u.mutation.ClearPost()
	return _u
}

// ClearTag clears the "tag" edge to the PostTag entity.
func (_u *PostTagRelationUpdateOne) ClearTag() *PostTagRelationUpdateOne {
	_u.mutation.ClearTag()
	return _u
}

// Where appends a list predicates to the PostTagRelationUpdate builder.
func (_u *PostTagRelationUpdateOne) Where(ps ...predicate.PostTagRelation) *PostTagRelationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PostTagRelationUpdateOne) Select(field string, fields ...string) *PostTagRelationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PostTagRelation entity.
func (_u *PostTagRelationUpdateOne) Save(ctx context.Context) (*PostTagRelation, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PostTagRelationUpdateOne) SaveX(ctx context.Context) *PostTagRelation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PostTagRelationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PostTagRelationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PostTagRelationUpdateOne) check() error {
	if _u.mutation.PostCleared() && len(_u.mutation.PostIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PostTagRelation.post"`)
	}
	if _u.mutation.TagCleared() && len(_u.mutation.TagIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PostTagRelation.tag"`)
	}
	return nil
}

func (_u *PostTagRelationUpdateOne) sqlSave(ctx context.Context) (_node *PostTagRelation, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(posttagrelation.Table, posttagrelation.Columns, sqlgraph.NewFieldSpec(posttagrelation.FieldPostID, field.TypeUint), sqlgraph.NewFieldSpec(posttagrelation.FieldPostTagID, field.TypeUint))
	if id, ok := _u.mutation.PostID(); !ok {
		return nil, &ValidationError{Name: "post_id", err: errors.New(`ent: missing "PostTagRelation.post_id" for update`)}
	} else {
		_spec.Node.CompositeID[0].Value = id
	}
	if id, ok := _u.mutation.PostTagID(); !ok {
		return nil, &ValidationError{Name: "post_tag_id", err: errors.New(`ent: missing "PostTagRelation.post_tag_id" for update`)}
	} else {
		_spec.Node.CompositeID[1].Value = id
	}
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, len(fields))
		for i, f := range fields {
			if !posttagrelation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			_spec.Node.Columns[i] = f
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.PostCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   posttagrelation.PostTable,
			Columns: []string{posttagrelation.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   posttagrelation.PostTable,
			Columns: []string{posttagrelation.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TagCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   posttagrelation.TagTable,
			Columns: []string{posttagrelation.TagColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(posttag.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TagIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   posttagrelation.TagTable,
			Columns: []string{posttagrelation.TagColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(posttag.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PostTagRelation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{posttagrelation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
