// Code generated by ent, DO NOT EDIT.

package ent

import (
	"blog-server/ent/post"
	"blog-server/ent/postcategory"
	"blog-server/ent/postcategoryrelation"
	"blog-server/ent/predicate"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PostCategoryRelationUpdate is the builder for updating PostCategoryRelation entities.
type PostCategoryRelationUpdate struct {
	config
	hooks    []Hook
	mutation *PostCategoryRelationMutation
}

// Where appends a list predicates to the PostCategoryRelationUpdate builder.
func (_u *PostCategoryRelationUpdate) Where(ps ...predicate.PostCategoryRelation) *PostCategoryRelationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPostID sets the "post_id" field.
func (_u *PostCategoryRelationUpdate) SetPostID(v uint) *PostCategoryRelationUpdate {
	_u.mutation.SetPostID(v)
	return _u
}

// SetNillablePostID sets the "post_id" field if the given value is not nil.
func (_u *PostCategoryRelationUpdate) SetNillablePostID(v *uint) *PostCategoryRelationUpdate {
	if v != nil {
		_u.SetPostID(*v)
	}
	return _u
}

// SetPostCategoryID sets the "post_category_id" field.
func (_u *PostCategoryRelationUpdate) SetPostCategoryID(v uint) *PostCategoryRelationUpdate {
	_u.mutation.SetPostCategoryID(v)
	return _u
}

// SetNillablePostCategoryID sets the "post_category_id" field if the given value is not nil.
func (_u *PostCategoryRelationUpdate) SetNillablePostCategoryID(v *uint) *PostCategoryRelationUpdate {
	if v != nil {
		_u.SetPostCategoryID(*v)
	}
	return _u
}

// SetPost sets the "post" edge to the Post entity.
func (_u *PostCategoryRelationUpdate) SetPost(v *Post) *PostCategoryRelationUpdate {
	return _u.SetPostID(v.ID)
}

// SetCategoryID sets the "category" edge to the PostCategory entity by ID.
func (_u *PostCategoryRelationUpdate) SetCategoryID(id uint) *PostCategoryRelationUpdate {
	_u.mutation.SetCategoryID(id)
	return _u
}

// SetCategory sets the "category" edge to the PostCategory entity.
func (_u *PostCategoryRelationUpdate) SetCategory(v *PostCategory) *PostCategoryRelationUpdate {
	return _u.SetCategoryID(v.ID)
}

// Mutation returns the PostCategoryRelationMutation object of the builder.
func (_u *PostCategoryRelationUpdate) Mutation() *PostCategoryRelationMutation {
	return _u.mutation
}

// ClearPost clears the "post" edge to the Post entity.
func (_u *PostCategoryRelationUpdate) ClearPost() *PostCategoryRelationUpdate {
	_u.mutation.ClearPost()
	return _u
}

// ClearCategory clears the "category" edge to the PostCategory entity.
func (_u *PostCategoryRelationUpdate) ClearCategory() *PostCategoryRelationUpdate {
	_u.mutation.ClearCategory()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PostCategoryRelationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PostCategoryRelationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PostCategoryRelationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PostCategoryRelationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PostCategoryRelationUpdate) check() error {
	if _u.mutation.PostCleared() && len(_u.mutation.PostIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PostCategoryRelation.post"`)
	}
	if _u.mutation.CategoryCleared() && len(_u.mutation.CategoryIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PostCategoryRelation.category"`)
	}
	return nil
}

func (_u *PostCategoryRelationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(postcategoryrelation.Table, postcategoryrelation.Columns, sqlgraph.NewFieldSpec(postcategoryrelation.FieldPostID, field.TypeUint), sqlgraph.NewFieldSpec(postcategoryrelation.FieldPostCategoryID, field.TypeUint))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.PostCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   postcategoryrelation.PostTable,
			Columns: []string{postcategoryrelation.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   postcategoryrelation.PostTable,
			Columns: []string{postcategoryrelation.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CategoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   postcategoryrelation.CategoryTable,
			Columns: []string{postcategoryrelation.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(postcategory.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   postcategoryrelation.CategoryTable,
			Columns: []string{postcategoryrelation.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(postcategory.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{postcategoryrelation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PostCategoryRelationUpdateOne is the builder for updating a single PostCategoryRelation entity.
type PostCategoryRelationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PostCategoryRelationMutation
}

// SetPostID sets the "post_id" field.
func (_u *PostCategoryRelationUpdateOne) SetPostID(v uint) *PostCategoryRelationUpdateOne {
	_u.mutation.SetPostID(v)
	return _u
}

// SetNillablePostID sets the "post_id" field if the given value is not nil.
func (_u *PostCategoryRelationUpdateOne) SetNillablePostID(v *uint) *PostCategoryRelationUpdateOne {
	if v != nil {
		_u.SetPostID(*v)
	}
	return _u
}

// SetPostCategoryID sets the "post_category_id" field.
func (_u *PostCategoryRelationUpdateOne) SetPostCategoryID(v uint) *PostCategoryRelationUpdateOne {
	_u.mutation.SetPostCategoryID(v)
	return _u
}

// SetNillablePostCategoryID sets the "post_category_id" field if the given value is not nil.
func (_u *PostCategoryRelationUpdateOne) SetNillablePostCategoryID(v *uint) *PostCategoryRelationUpdateOne {
	if v != nil {
		_u.SetPostCategoryID(*v)
	}
	return _u
}

// SetPost sets the "post" edge to the Post entity.
func (_u *PostCategoryRelationUpdateOne) SetPost(v *Post) *PostCategoryRelationUpdateOne {
	return _u.SetPostID(v.ID)
}

// SetCategoryID sets the "category" edge to the PostCategory entity by ID.
func (_u *PostCategoryRelationUpdateOne) SetCategoryID(id uint) *PostCategoryRelationUpdateOne {
	_u.mutation.SetCategoryID(id)
	return _u
}

// SetCategory sets the "category" edge to the PostCategory entity.
func (_u *PostCategoryRelationUpdateOne) SetCategory(v *PostCategory) *PostCategoryRelationUpdateOne {
	return _u.SetCategoryID(v.ID)
}

// Mutation returns the PostCategoryRelationMutation object of the builder.
func (_u *PostCategoryRelationUpdateOne) Mutation() *PostCategoryRelationMutation {
	return _u.mutation
}

// ClearPost clears the "post" edge to the Post entity.
func (_u *PostCategoryRelationUpdateOne) ClearPost() *PostCategoryRelationUpdateOne {
	_u.mutation.ClearPost()
	return _u
}

// ClearCategory clears the "category" edge to the PostCategory entity.
func (_u *PostCategoryRelationUpdateOne) ClearCategory() *PostCategoryRelationUpdateOne {
	_u.mutation.ClearCategory()
	return _u
}

// Where appends a list predicates to the PostCategoryRelationUpdate builder.
func (_u *PostCategoryRelationUpdateOne) Where(ps ...predicate.PostCategoryRelation) *PostCategoryRelationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PostCategoryRelationUpdateOne) Select(field string, fields ...string) *PostCategoryRelationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PostCategoryRelation entity.
func (_u *PostCategoryRelationUpdateOne) Save(ctx context.Context) (*PostCategoryRelation, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PostCategoryRelationUpdateOne) SaveX(ctx context.Context) *PostCategoryRelation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PostCategoryRelationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PostCategoryRelationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PostCategoryRelationUpdateOne) check() error {
	if _u.mutation.PostCleared() && len(_u.mutation.PostIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PostCategoryRelation.post"`)
	}
	if _u.mutation.CategoryCleared() && len(_u.mutation.CategoryIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PostCategoryRelation.category"`)
	}
	return nil
}

func (_u *PostCategoryRelationUpdateOne) sqlSave(ctx context.Context) (_node *PostCategoryRelation, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(postcategoryrelation.Table, postcategoryrelation.Columns, sqlgraph.NewFieldSpec(postcategoryrelation.FieldPostID, field.TypeUint), sqlgraph.NewFieldSpec(postcategoryrelation.FieldPostCategoryID, field.TypeUint))
	if id, ok := _u.mutation.PostID(); !ok {
		return nil, &ValidationError{Name: "post_id", err: errors.New(`ent: missing "PostCategoryRelation.post_id" for update`)}
	} else {
		_spec.Node.CompositeID[0].Value = id
	}
	if id, ok := _u.mutation.PostCategoryID(); !ok {
		return nil, &ValidationError{Name: "post_category_id", err: errors.New(`ent: missing "PostCategoryRelation.post_category_id" for update`)}
	} else {
		_spec.Node.CompositeID[1].Value = id
	}
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, len(fields))
		for i, f := range fields {
			if !postcategoryrelation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			_spec.Node.Columns[i] = f
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.PostCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   postcategoryrelation.PostTable,
			Columns: []string{postcategoryrelation.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   postcategoryrelation.PostTable,
			Columns: []string{postcategoryrelation.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CategoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   postcategoryrelation.CategoryTable,
			Columns: []string{postcategoryrelation.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(postcategory.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   postcategoryrelation.CategoryTable,
			Columns: []string{postcategoryrelation.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(postcategory.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PostCategoryRelation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{postcategoryrelation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
