// Code generated by ent, DO NOT EDIT.

package ent

import (
	"blog-server/ent/post"
	"blog-server/ent/postcategory"
	"blog-server/ent/posttag"
	"blog-server/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PostCreate is the builder for creating a Post entity.
type PostCreate struct {
	config
	mutation *PostMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *PostCreate) SetCreatedAt(v time.Time) *PostCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PostCreate) SetNillableCreatedAt(v *time.Time) *PostCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PostCreate) SetUpdatedAt(v time.Time) *PostCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PostCreate) SetNillableUpdatedAt(v *time.Time) *PostCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *PostCreate) SetDeletedAt(v time.Time) *PostCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *PostCreate) SetNillableDeletedAt(v *time.Time) *PostCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *PostCreate) SetUserID(v uint) *PostCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *PostCreate) SetTitle(v string) *PostCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetSummary sets the "summary" field.
func (_c *PostCreate) SetSummary(v string) *PostCreate {
	_c.mutation.SetSummary(v)
	return _c
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_c *PostCreate) SetNillableSummary(v *string) *PostCreate {
	if v != nil {
		_c.SetSummary(*v)
	}
	return _c
}

// SetContent sets the "content" field.
func (_c *PostCreate) SetContent(v string) *PostCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetCover sets the "cover" field.
func (_c *PostCreate) SetCover(v string) *PostCreate {
	_c.mutation.SetCover(v)
	return _c
}

// SetNillableCover sets the "cover" field if the given value is not nil.
func (_c *PostCreate) SetNillableCover(v *string) *PostCreate {
	if v != nil {
		_c.SetCover(*v)
	}
	return _c
}

// SetReadTimeMinutes sets the "read_time_minutes" field.
func (_c *PostCreate) SetReadTimeMinutes(v uint) *PostCreate {
	_c.mutation.SetReadTimeMinutes(v)
	return _c
}

// SetViewCount sets the "view_count" field.
func (_c *PostCreate) SetViewCount(v uint) *PostCreate {
	_c.mutation.SetViewCount(v)
	return _c
}

// SetNillableViewCount sets the "view_count" field if the given value is not nil.
func (_c *PostCreate) SetNillableViewCount(v *uint) *PostCreate {
	if v != nil {
		_c.SetViewCount(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *PostCreate) SetStatus(v post.Status) *PostCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *PostCreate) SetNillableStatus(v *post.Status) *PostCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetPublishedAt sets the "published_at" field.
func (_c *PostCreate) SetPublishedAt(v time.Time) *PostCreate {
	_c.mutation.SetPublishedAt(v)
	return _c
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_c *PostCreate) SetNillablePublishedAt(v *time.Time) *PostCreate {
	if v != nil {
		_c.SetPublishedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PostCreate) SetID(v uint) *PostCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetAuthorID sets the "author" edge to the User entity by ID.
func (_c *PostCreate) SetAuthorID(id uint) *PostCreate {
	_c.mutation.SetAuthorID(id)
	return _c
}

// SetAuthor sets the "author" edge to the User entity.
func (_c *PostCreate) SetAuthor(v *User) *PostCreate {
	return _c.SetAuthorID(v.ID)
}

// AddCategoryIDs adds the "categories" edge to the PostCategory entity by IDs.
func (_c *PostCreate) AddCategoryIDs(ids ...uint) *PostCreate {
	_c.mutation.AddCategoryIDs(ids...)
	return _c
}

// AddCategories adds the "categories" edges to the PostCategory entity.
func (_c *PostCreate) AddCategories(v ...*PostCategory) *PostCreate {
	ids := make([]uint, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCategoryIDs(ids...)
}

// AddTagIDs adds the "tags" edge to the PostTag entity by IDs.
func (_c *PostCreate) AddTagIDs(ids ...uint) *PostCreate {
	_c.mutation.AddTagIDs(ids...)
	return _c
}

// AddTags adds the "tags" edges to the PostTag entity.
func (_c *PostCreate) AddTags(v ...*PostTag) *PostCreate {
	ids := make([]uint, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTagIDs(ids...)
}

// Mutation returns the PostMutation object of the builder.
func (_c *PostCreate) Mutation() *PostMutation {
	return _c.mutation
}

// Save creates the Post in the database.
func (_c *PostCreate) Save(ctx context.Context) (*Post, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PostCreate) SaveX(ctx context.Context) *Post {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PostCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PostCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PostCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if post.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized post.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := post.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if post.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized post.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := post.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ViewCount(); !ok {
		v := post.DefaultViewCount
		_c.mutation.SetViewCount(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := post.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *PostCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Post.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Post.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Post.user_id"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Post.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := post.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Post.title": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Summary(); ok {
		if err := post.SummaryValidator(v); err != nil {
			return &ValidationError{Name: "summary", err: fmt.Errorf(`ent: validator failed for field "Post.summary": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "Post.content"`)}
	}
	if v, ok := _c.mutation.Cover(); ok {
		if err := post.CoverValidator(v); err != nil {
			return &ValidationError{Name: "cover", err: fmt.Errorf(`ent: validator failed for field "Post.cover": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ReadTimeMinutes(); !ok {
		return &ValidationError{Name: "read_time_minutes", err: errors.New(`ent: missing required field "Post.read_time_minutes"`)}
	}
	if _, ok := _c.mutation.ViewCount(); !ok {
		return &ValidationError{Name: "view_count", err: errors.New(`ent: missing required field "Post.view_count"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Post.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := post.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Post.status": %w`, err)}
		}
	}
	if len(_c.mutation.AuthorIDs()) == 0 {
		return &ValidationError{Name: "author", err: errors.New(`ent: missing required edge "Post.author"`)}
	}
	return nil
}

func (_c *PostCreate) sqlSave(ctx context.Context) (*Post, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PostCreate) createSpec() (*Post, *sqlgraph.CreateSpec) {
	var (
		_node = &Post{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(post.Table, sqlgraph.NewFieldSpec(post.FieldID, field.TypeUint))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(post.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(post.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(post.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(post.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Summary(); ok {
		_spec.SetField(post.FieldSummary, field.TypeString, value)
		_node.Summary = &value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(post.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.Cover(); ok {
		_spec.SetField(post.FieldCover, field.TypeString, value)
		_node.Cover = &value
	}
	if value, ok := _c.mutation.ReadTimeMinutes(); ok {
		_spec.SetField(post.FieldReadTimeMinutes, field.TypeUint, value)
		_node.ReadTimeMinutes = value
	}
	if value, ok := _c.mutation.ViewCount(); ok {
		_spec.SetField(post.FieldViewCount, field.TypeUint, value)
		_node.ViewCount = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(post.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.PublishedAt(); ok {
		_spec.SetField(post.FieldPublishedAt, field.TypeTime, value)
		_node.PublishedAt = &value
	}
	if nodes := _c.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   post.AuthorTable,
			Columns: []string{post.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CategoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   post.CategoriesTable,
			Columns: post.CategoriesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(postcategory.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   post.TagsTable,
			Columns: post.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(posttag.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PostCreateBulk is the builder for creating many Post entities in bulk.
type PostCreateBulk struct {
	config
	err      error
	builders []*PostCreate
}

// Save creates the Post entities in the database.
func (_c *PostCreateBulk) Save(ctx context.Context) ([]*Post, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Post, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PostMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PostCreateBulk) SaveX(ctx context.Context) []*Post {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PostCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PostCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
