// Code generated by ent, DO NOT EDIT.

package ent

import (
	"blog-server/ent/post"
	"blog-server/ent/postcategory"
	"blog-server/ent/postcategoryrelation"
	"blog-server/ent/predicate"
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PostCategoryQuery is the builder for querying PostCategory entities.
type PostCategoryQuery struct {
	config
	ctx                       *QueryContext
	order                     []postcategory.OrderOption
	inters                    []Interceptor
	predicates                []predicate.PostCategory
	withPosts                 *PostQuery
	withPostCategoryRelations *PostCategoryRelationQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PostCategoryQuery builder.
func (_q *PostCategoryQuery) Where(ps ...predicate.PostCategory) *PostCategoryQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *PostCategoryQuery) Limit(limit int) *PostCategoryQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *PostCategoryQuery) Offset(offset int) *PostCategoryQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *PostCategoryQuery) Unique(unique bool) *PostCategoryQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *PostCategoryQuery) Order(o ...postcategory.OrderOption) *PostCategoryQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryPosts chains the current query on the "posts" edge.
func (_q *PostCategoryQuery) QueryPosts() *PostQuery {
	query := (&PostClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(postcategory.Table, postcategory.FieldID, selector),
			sqlgraph.To(post.Table, post.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, postcategory.PostsTable, postcategory.PostsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPostCategoryRelations chains the current query on the "post_category_relations" edge.
func (_q *PostCategoryQuery) QueryPostCategoryRelations() *PostCategoryRelationQuery {
	query := (&PostCategoryRelationClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(postcategory.Table, postcategory.FieldID, selector),
			sqlgraph.To(postcategoryrelation.Table, postcategoryrelation.CategoryColumn),
			sqlgraph.Edge(sqlgraph.O2M, true, postcategory.PostCategoryRelationsTable, postcategory.PostCategoryRelationsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PostCategory entity from the query.
// Returns a *NotFoundError when no PostCategory was found.
func (_q *PostCategoryQuery) First(ctx context.Context) (*PostCategory, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{postcategory.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *PostCategoryQuery) FirstX(ctx context.Context) *PostCategory {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PostCategory ID from the query.
// Returns a *NotFoundError when no PostCategory ID was found.
func (_q *PostCategoryQuery) FirstID(ctx context.Context) (id uint, err error) {
	var ids []uint
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{postcategory.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *PostCategoryQuery) FirstIDX(ctx context.Context) uint {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PostCategory entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PostCategory entity is found.
// Returns a *NotFoundError when no PostCategory entities are found.
func (_q *PostCategoryQuery) Only(ctx context.Context) (*PostCategory, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{postcategory.Label}
	default:
		return nil, &NotSingularError{postcategory.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *PostCategoryQuery) OnlyX(ctx context.Context) *PostCategory {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PostCategory ID in the query.
// Returns a *NotSingularError when more than one PostCategory ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *PostCategoryQuery) OnlyID(ctx context.Context) (id uint, err error) {
	var ids []uint
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{postcategory.Label}
	default:
		err = &NotSingularError{postcategory.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *PostCategoryQuery) OnlyIDX(ctx context.Context) uint {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PostCategories.
func (_q *PostCategoryQuery) All(ctx context.Context) ([]*PostCategory, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PostCategory, *PostCategoryQuery]()
	return withInterceptors[[]*PostCategory](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *PostCategoryQuery) AllX(ctx context.Context) []*PostCategory {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PostCategory IDs.
func (_q *PostCategoryQuery) IDs(ctx context.Context) (ids []uint, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(postcategory.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *PostCategoryQuery) IDsX(ctx context.Context) []uint {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *PostCategoryQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*PostCategoryQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *PostCategoryQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *PostCategoryQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *PostCategoryQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PostCategoryQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *PostCategoryQuery) Clone() *PostCategoryQuery {
	if _q == nil {
		return nil
	}
	return &PostCategoryQuery{
		config:                    _q.config,
		ctx:                       _q.ctx.Clone(),
		order:                     append([]postcategory.OrderOption{}, _q.order...),
		inters:                    append([]Interceptor{}, _q.inters...),
		predicates:                append([]predicate.PostCategory{}, _q.predicates...),
		withPosts:                 _q.withPosts.Clone(),
		withPostCategoryRelations: _q.withPostCategoryRelations.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithPosts tells the query-builder to eager-load the nodes that are connected to
// the "posts" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PostCategoryQuery) WithPosts(opts ...func(*PostQuery)) *PostCategoryQuery {
	query := (&PostClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPosts = query
	return _q
}

// WithPostCategoryRelations tells the query-builder to eager-load the nodes that are connected to
// the "post_category_relations" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PostCategoryQuery) WithPostCategoryRelations(opts ...func(*PostCategoryRelationQuery)) *PostCategoryQuery {
	query := (&PostCategoryRelationClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPostCategoryRelations = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PostCategory.Query().
//		GroupBy(postcategory.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *PostCategoryQuery) GroupBy(field string, fields ...string) *PostCategoryGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PostCategoryGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = postcategory.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.PostCategory.Query().
//		Select(postcategory.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *PostCategoryQuery) Select(fields ...string) *PostCategorySelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &PostCategorySelect{PostCategoryQuery: _q}
	sbuild.label = postcategory.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PostCategorySelect configured with the given aggregations.
func (_q *PostCategoryQuery) Aggregate(fns ...AggregateFunc) *PostCategorySelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *PostCategoryQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !postcategory.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *PostCategoryQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PostCategory, error) {
	var (
		nodes       = []*PostCategory{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withPosts != nil,
			_q.withPostCategoryRelations != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PostCategory).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PostCategory{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withPosts; query != nil {
		if err := _q.loadPosts(ctx, query, nodes,
			func(n *PostCategory) { n.Edges.Posts = []*Post{} },
			func(n *PostCategory, e *Post) { n.Edges.Posts = append(n.Edges.Posts, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withPostCategoryRelations; query != nil {
		if err := _q.loadPostCategoryRelations(ctx, query, nodes,
			func(n *PostCategory) { n.Edges.PostCategoryRelations = []*PostCategoryRelation{} },
			func(n *PostCategory, e *PostCategoryRelation) {
				n.Edges.PostCategoryRelations = append(n.Edges.PostCategoryRelations, e)
			}); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *PostCategoryQuery) loadPosts(ctx context.Context, query *PostQuery, nodes []*PostCategory, init func(*PostCategory), assign func(*PostCategory, *Post)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[uint]*PostCategory)
	nids := make(map[uint]map[*PostCategory]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(postcategory.PostsTable)
		s.Join(joinT).On(s.C(post.FieldID), joinT.C(postcategory.PostsPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(postcategory.PostsPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(postcategory.PostsPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := uint(values[0].(*sql.NullInt64).Int64)
				inValue := uint(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*PostCategory]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Post](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "posts" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (_q *PostCategoryQuery) loadPostCategoryRelations(ctx context.Context, query *PostCategoryRelationQuery, nodes []*PostCategory, init func(*PostCategory), assign func(*PostCategory, *PostCategoryRelation)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uint]*PostCategory)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(postcategoryrelation.FieldPostCategoryID)
	}
	query.Where(predicate.PostCategoryRelation(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(postcategory.PostCategoryRelationsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.PostCategoryID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "post_category_id" returned %v for node %v`, fk, n)
		}
		assign(node, n)
	}
	return nil
}

func (_q *PostCategoryQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *PostCategoryQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(postcategory.Table, postcategory.Columns, sqlgraph.NewFieldSpec(postcategory.FieldID, field.TypeUint))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, postcategory.FieldID)
		for i := range fields {
			if fields[i] != postcategory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *PostCategoryQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(postcategory.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = postcategory.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PostCategoryGroupBy is the group-by builder for PostCategory entities.
type PostCategoryGroupBy struct {
	selector
	build *PostCategoryQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *PostCategoryGroupBy) Aggregate(fns ...AggregateFunc) *PostCategoryGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *PostCategoryGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PostCategoryQuery, *PostCategoryGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *PostCategoryGroupBy) sqlScan(ctx context.Context, root *PostCategoryQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PostCategorySelect is the builder for selecting fields of PostCategory entities.
type PostCategorySelect struct {
	*PostCategoryQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *PostCategorySelect) Aggregate(fns ...AggregateFunc) *PostCategorySelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *PostCategorySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PostCategoryQuery, *PostCategorySelect](ctx, _s.PostCategoryQuery, _s, _s.inters, v)
}

func (_s *PostCategorySelect) sqlScan(ctx context.Context, root *PostCategoryQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
