// Code generated by ent, DO NOT EDIT.

package ent

import (
	"blog-server/ent/post"
	"blog-server/ent/posttag"
	"blog-server/ent/posttagrelation"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PostTagRelationCreate is the builder for creating a PostTagRelation entity.
type PostTagRelationCreate struct {
	config
	mutation *PostTagRelationMutation
	hooks    []Hook
}

// SetPostID sets the "post_id" field.
func (_c *PostTagRelationCreate) SetPostID(v uint) *PostTagRelationCreate {
	_c.mutation.SetPostID(v)
	return _c
}

// SetPostTagID sets the "post_tag_id" field.
func (_c *PostTagRelationCreate) SetPostTagID(v uint) *PostTagRelationCreate {
	_c.mutation.SetPostTagID(v)
	return _c
}

// SetPost sets the "post" edge to the Post entity.
func (_c *PostTagRelationCreate) SetPost(v *Post) *PostTagRelationCreate {
	return _c.SetPostID(v.ID)
}

// SetTagID sets the "tag" edge to the PostTag entity by ID.
func (_c *PostTagRelationCreate) SetTagID(id uint) *PostTagRelationCreate {
	_c.mutation.SetTagID(id)
	return _c
}

// SetTag sets the "tag" edge to the PostTag entity.
func (_c *PostTagRelationCreate) SetTag(v *PostTag) *PostTagRelationCreate {
	return _c.SetTagID(v.ID)
}

// Mutation returns the PostTagRelationMutation object of the builder.
func (_c *PostTagRelationCreate) Mutation() *PostTagRelationMutation {
	return _c.mutation
}

// Save creates the PostTagRelation in the database.
func (_c *PostTagRelationCreate) Save(ctx context.Context) (*PostTagRelation, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PostTagRelationCreate) SaveX(ctx context.Context) *PostTagRelation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PostTagRelationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PostTagRelationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PostTagRelationCreate) check() error {
	if _, ok := _c.mutation.PostID(); !ok {
		return &ValidationError{Name: "post_id", err: errors.New(`ent: missing required field "PostTagRelation.post_id"`)}
	}
	if _, ok := _c.mutation.PostTagID(); !ok {
		return &ValidationError{Name: "post_tag_id", err: errors.New(`ent: missing required field "PostTagRelation.post_tag_id"`)}
	}
	if len(_c.mutation.PostIDs()) == 0 {
		return &ValidationError{Name: "post", err: errors.New(`ent: missing required edge "PostTagRelation.post"`)}
	}
	if len(_c.mutation.TagIDs()) == 0 {
		return &ValidationError{Name: "tag", err: errors.New(`ent: missing required edge "PostTagRelation.tag"`)}
	}
	return nil
}

func (_c *PostTagRelationCreate) sqlSave(ctx context.Context) (*PostTagRelation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}

func (_c *PostTagRelationCreate) createSpec() (*PostTagRelation, *sqlgraph.CreateSpec) {
	var (
		_node = &PostTagRelation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(posttagrelation.Table, nil)
	)
	if nodes := _c.mutation.PostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   posttagrelation.PostTable,
			Columns: []string{posttagrelation.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PostID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TagIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   posttagrelation.TagTable,
			Columns: []string{posttagrelation.TagColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(posttag.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PostTagID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PostTagRelationCreateBulk is the builder for creating many PostTagRelation entities in bulk.
type PostTagRelationCreateBulk struct {
	config
	err      error
	builders []*PostTagRelationCreate
}

// Save creates the PostTagRelation entities in the database.
func (_c *PostTagRelationCreateBulk) Save(ctx context.Context) ([]*PostTagRelation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PostTagRelation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PostTagRelationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PostTagRelationCreateBulk) SaveX(ctx context.Context) []*PostTagRelation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PostTagRelationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PostTagRelationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
