// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Comment is the predicate function for comment builders.
type Comment func(*sql.Selector)

// Link is the predicate function for link builders.
type Link func(*sql.Selector)

// LinkCategory is the predicate function for linkcategory builders.
type LinkCategory func(*sql.Selector)

// Post is the predicate function for post builders.
type Post func(*sql.Selector)

// PostCategory is the predicate function for postcategory builders.
type PostCategory func(*sql.Selector)

// PostCategoryRelation is the predicate function for postcategoryrelation builders.
type PostCategoryRelation func(*sql.Selector)

// PostTag is the predicate function for posttag builders.
type PostTag func(*sql.Selector)

// PostTagRelation is the predicate function for posttagrelation builders.
type PostTagRelation func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
